In [5]:
import numpy as np

In [6]:
sample_matrix=np.array([[24,13,2,15],[15,2,54,65],[56,76,24,7]])
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [7]:
sample_matrix[2,3]

7

In [8]:
sample_matrix[2][3]

7

In [15]:
sample_matrix[:3]

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [16]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [18]:
sample_matrix[1,1]

2

In [19]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [21]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [22]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [23]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [24]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [25]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [26]:
np.max(sample_array)

30

In [27]:
np.min(sample_array)

1

In [28]:
np.argmax(sample_array)

29

In [29]:
np.argmin(sample_array)

0

In [30]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900])

In [32]:
np.std(sample_array)

8.65544144839919

In [33]:
np.var(sample_array)

74.91666666666667

In [34]:
np.mean(sample_array)

15.5

In [35]:
array=np.random.randn(3,4)  ### normal distribution
array

array([[ 0.59711014, -2.62697993, -0.76670194, -0.15465229],
       [ 1.26875574, -0.66052956,  0.76231016, -1.86131627],
       [ 1.67448837, -0.40190128, -0.65215893,  0.80546458]])

In [36]:
np.round(array,decimals=4)

array([[ 0.5971, -2.627 , -0.7667, -0.1547],
       [ 1.2688, -0.6605,  0.7623, -1.8613],
       [ 1.6745, -0.4019, -0.6522,  0.8055]])

In [37]:
sports=np.array(["golf","cricket","fball","football"])
np.unique(sports)

array(['cricket', 'fball', 'football', 'golf'], dtype='<U8')

In [38]:
sports=np.array(["golf","cricket","volleyball","football"])
np.unique(sports)

array(['cricket', 'football', 'golf', 'volleyball'], dtype='<U10')

In [39]:
sports=np.array(["artificialintelligence","cricket","volleyball","football"])
np.unique(sports)

array(['artificialintelligence', 'cricket', 'football', 'volleyball'],
      dtype='<U22')